### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by PlanetDreams** [wanchain/wanwallet#7]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `3.0.26`
OS & Version: windows 
Node version: `geth 1.0.9` 
Number of blocks synchronized: 3,458,558
```

Hello there . I can enter my wallet but cant send anything from the wallet because i forgot my password to confirm the transaction .How can i restore my password?

**Comment by lolieatcat** [comment]
Password cannot restore anyway. You can try to create a new account to use.

**Comment by lolieatcat** [comment]
If the password could be restored, the wallet will not secure. Anybody can get your money if he copies your keystore file.
